version: '3'
services:
  mysql:
    image: mysql:5.7
    environment:
    - MYSQL_ROOT_PASSWORD=xenon-slurm-pw
    healthcheck:
      test: mysqladmin -pxenon-slurm-pw ping || exit 1
      interval: 1s
      timeout: 1s
      retries: 1
  slurm:
    image: nlesc/xenon-slurm-15
    depends_on:
    - mysql
    ports:
    - 22 # ssh
    - 6817 # slurm controller
    healthcheck:
      test: sinfo || exit 1
      interval: 1s
      timeout: 1s
      retries: 1
